タブ表示テスト
teramotodaiki/hackforplay-editor pull request #24
Opened 2016-09-20 13:14 UTC by tenonno

進捗どうですか

2016-09-20 13:32 UTC, teramotodaiki requested changes
CSSは.cssファイルに書きたいので、BEMっぽいcssを使って動的な部分を削っていこう（提案

.ReactCodeMirror__tab-visible .cm-tab:before {
    visibility: true;
}

<CodeMirror ... className={tabVisble ? "ReactCodeMirror__tab-visible" : ""} />

2016-09-20 13:34 UTC, teramotodaiki approved these changes

2016-09-20 13:35 UTC, teramotodaiki commented
ブッブーって感じになった…ごめんよ…

2016-09-20 14:06 UTC, tenonno commented
修正したべ

2016-09-21 06:53 UTC, teramotodaiki commented
Awesome! Thanks your PR :-)

タブの可視化だけでなく、バグフィックスまで！
この霊夢…デキる

2016-09-21 06:53 UTC, merged